### DISCUSSION TITLE
docker 部署没有起来

### DISCUSSION THREAD

**Discussion by guinanlin** [heyform/heyform#15] [Self hosting]
部署后显示运行都正常， 但是访问 http://192.168.8.92:9091 没法访问

docker.env

```
[root@ERPNext-Basic-guanfangbanbenyanshi heyform]# cat docker.env
# https://docs.heyform.net/configuration

# App serve
# If you are developing locally, you can use http://[ip]:[port].
APP_HOMEPAGE_URL=http://192.168.8.92:9091

# If you are using docker:
# ports:
#  - "9090:8000"
# The url should be http://127.0.0.1:9090 but not :8000.

# If you are deploying to a server, please replace it with your domain.
# APP_HOMEPAGE_URL=https://heyform.net

# Auth
SESSION_MAX_AGE=15d
SESSION_KEY="key1"
FORM_ENCRYPTION_KEY="key2"

# Mongo
MONGO_URI="mongodb://localhost:27017/heyform"
MONGO_USER=
MONGO_PASSWORD=

# Upload
UPLOAD_FILE_TYPES=".jpg,.png,.bmp,.gif,.txt,.md,.doc,.docx,.xls,.xlsx,.csv,.ppt,.pptx,.pdf,.mp4,.wmv,.zip,.rar,.7z"

# SMTP
SMTP_FROM="HeyForm <noreply@example.com>"
SMTP_HOST="example.com"
SMTP_PORT=465
SMTP_USER=
SMTP_PASSWORD=

# Social login
APPLE_LOGIN_TEAM_ID=
APPLE_LOGIN_WEB_CLIENT_ID=
APPLE_LOGIN_KEY_ID=
APPLE_LOGIN_PRIVATE_KEY_PATH=

# https://docs.heyform.net/login-with-google
GOOGLE_LOGIN_CLIENT_ID=
GOOGLE_LOGIN_CLIENT_SECRET=

# Submission spam filter
AKISMET_KEY=

# Anti bot
# https://www.geetest.com/en/
GEETEST_CAPTCHA_ID=
GEETEST_CAPTCHA_KEY=

# https://www.google.com/recaptcha/about/
GOOGLE_RECAPTCHA_KEY=
GOOGLE_RECAPTCHA_SECRET=

# Bull & redis
BULL_JOB_ATTEMPTS=3
BULL_JOB_BACKOFF_DELAY=3000
BULL_JOB_BACKOFF_TYPE=fixed

REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_DB=0

# Unsplash
UNSPLASH_CLIENT_ID=

# Stripe
# https://docs.heyform.net/connect-with-stripe
STRIPE_PUBLISHABLE_KEY=pk_
STRIPE_SECRET_KEY=sk_
STRIPE_CONNECT_CLIENT_ID=ca_
STRIPE_WEBHOOK_SECRET_KEY=whsec_
```

docker-compose.yml

```
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    restart: "always"
    env_file: ./docker.env
    ports:
      - "9091:8000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "26379:6379"
```

**Comment by iMuFeng** [comment]
Is it possible to access http://127.0.0.1:9091?

**Reply by guinanlin** [reply]
not , but seems ports work well.

```
[root@ERPNext-Basic-guanfangbanbenyanshi heyform]# netstat -lantp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5090            0.0.0.0:*               LISTEN      2419/docker-proxy   
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      1320/docker-proxy   
tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      8895/docker-proxy   
tcp        0      0 0.0.0.0:5091            0.0.0.0:*               LISTEN      2399/docker-proxy   
tcp        0      0 0.0.0.0:5092            0.0.0.0:*               LISTEN      2360/docker-proxy   
tcp        0      0 0.0.0.0:5093            0.0.0.0:*               LISTEN      2341/docker-proxy   
tcp        0      0 0.0.0.0:5094            0.0.0.0:*               LISTEN      2320/docker-proxy   
tcp        0      0 0.0.0.0:5095            0.0.0.0:*               LISTEN      2301/docker-proxy   
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      1798/docker-proxy   
tcp        0      0 0.0.0.0:26379           0.0.0.0:*               LISTEN      1820/docker-proxy   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      815/sshd            
tcp        0      0 0.0.0.0:5080            0.0.0.0:*               LISTEN      2539/docker-proxy   
tcp        0      0 0.0.0.0:5081            0.0.0.0:*               LISTEN      2519/docker-proxy   
tcp        0      0 0.0.0.0:5082            0.0.0.0:*               LISTEN      2499/docker-proxy   
tcp        0      0 0.0.0.0:5306            0.0.0.0:*               LISTEN      2379/docker-proxy   
tcp        0      0 0.0.0.0:5083            0.0.0.0:*               LISTEN      2480/docker-proxy   
tcp        0      0 0.0.0.0:5084            0.0.0.0:*               LISTEN      2459/docker-proxy   
tcp        0      0 0.0.0.0:5085            0.0.0.0:*               LISTEN      2439/docker-proxy   
tcp        0    336 192.168.8.92:22         192.168.8.245:62207     ESTABLISHED 3145/sshd: root@pts 
tcp6       0      0 :::5090                 :::*                    LISTEN      2425/docker-proxy   
tcp6       0      0 :::9090                 :::*                    LISTEN      1326/docker-proxy   
tcp6       0      0 :::10050                :::*                    LISTEN      814/zabbix_agent2   
tcp6       0      0 :::9091                 :::*                    LISTEN      8901/docker-proxy   
tcp6       0      0 :::5091                 :::*                    LISTEN      2406/docker-proxy   
tcp6       0      0 :::5092                 :::*                    LISTEN      2366/docker-proxy   
tcp6       0      0 :::5093                 :::*                    LISTEN      2347/docker-proxy   
tcp6       0      0 :::5094                 :::*                    LISTEN      2326/docker-proxy   
tcp6       0      0 :::5095                 :::*                    LISTEN      2307/docker-proxy   
tcp6       0      0 :::2375                 :::*                    LISTEN      995/dockerd         
tcp6       0      0 :::27017                :::*                    LISTEN      1804/docker-proxy   
tcp6       0      0 :::26379                :::*                    LISTEN      1826/docker-proxy   
tcp6       0      0 :::5080                 :::*                    LISTEN      2545/docker-proxy   
tcp6       0      0 :::5081                 :::*                    LISTEN      2525/docker-proxy   
tcp6       0      0 :::5082                 :::*                    LISTEN      2506/docker-proxy   
tcp6       0      0 :::5306                 :::*                    LISTEN      2385/docker-proxy   
tcp6       0      0 :::5083                 :::*                    LISTEN      2487/docker-proxy   
tcp6       0      0 :::5084                 :::*                    LISTEN      2465/docker-proxy   
tcp6       0      0 :::5085                 :::*                    LISTEN      2446/docker-proxy   
tcp6       0      0 192.168.8.92:2375       192.168.8.102:52604     ESTABLISHED 995/dockerd         
[root@ERPNext-Basic-guanfangbanbenyanshi heyform]# ps -ef | grep 9090
root       1320    995  0 06:49 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9090 -container-ip 172.18.0.4 -container-port 8000
root       1326    995  0 06:49 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 9090 -container-ip 172.18.0.4 -container-port 8000
root       9071   3147  0 10:36 pts/0    00:00:00 grep --color=auto 9090
[root@ERPNext-Basic-guanfangbanbenyanshi heyform]# ps -ef | grep 9091
root       8895    995  0 10:32 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9091 -container-ip 172.18.0.4 -container-port 8000
root       8901    995  0 10:32 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 9091 -container-ip 172.18.0.4 -container-port 8000
root       9083   3147  0 10:36 pts/0    00:00:00 grep --color=auto 9091
```

**Comment by guinanlin** [comment]
借助另外一个帖子， 用这个跑起来了， 也能创建账号， 但是登录之后没法跳转，也是进不去。

```
version: "3"

services:
  heyform:
    container_name: heyform_app
    image: heyform/community-edition:latest
    ports:
      - "9091:8000"
    depends_on:
      - mongo
      - redis
    environment:
      APP_HOMEPAGE_URL: http://127.0.0.1:9091
      COOKIE_DOMAIN: 127.0.0.1
      SESSION_MAX_AGE: 15d
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform?authSource=admin"
      UPLOAD_FILE_TYPES: ".jpg,.png,.bmp,.gif,.txt,.md,.doc,.docx,.xls,.xlsx,.csv,.ppt,.pptx,.pdf,.mp4,.wmv,.zip,.rar,.7z"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  mongo:
    container_name: heyform_mongo
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"

  redis:
    container_name: heyform_redis
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "26379:6379"
```
