### DISCUSSION TITLE
heyform docker not starting up

### DISCUSSION THREAD

**Discussion by envy** [heyform/heyform#43] [Self hosting]
Hi,

I wanted to try out heyform and used the docker compose selfhosting example.

Sadly, my heyform container just crashes on startup with the following log:

```
> server@0.0.6 migrate:seed
> mongoose-cli seed --name apps.ts

[mongoose-cli] Using environment "undefined"
[mongoose-cli] apps.ts: migrating
[mongoose-cli] Invalid URL
```

I tried with `MONGO_URI` set to `mongodb://mongo:27017/heyform` (as in the example), I tried with the example showing mongo authentication. I also tried renaming the mongo container. In all cases, the heyform container starts up for about 8-10 secs and then restarts. The only log entries are the ones provided above over and over again.
I did replace the key environment variables with my own random values.

My mongodb and redis are fresh containers only for this purpose, there is nothing in them. They start up as expected.

**To Reproduce**
1. Go to https://docs.heyform.net/self-hosting and copy the "Run on your own computer" example
2. `docker compose up`
3. Look at the log of the restarting container

**Expected behavior**
heyform starts up.

**HeyForm (please complete the following information):**
- Install: self hosted
- Version: v0.0.6, `latest` container tag

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.3

**Comment by iMuFeng** [comment]
Can you paste your `docker-compose.yml` here?

**Reply by envy** [reply]
Sure:

```yaml
---
version: "3"
networks:
  traefik_bridge:
    external: true
  default:
volumes:
  data:
services:
  heyform:
    image: heyform/community-edition:latest
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    networks:
      - traefik_bridge
      - default
    environment:
      APP_HOMEPAGE_URL: "https://forms.mydomain.com"
      SESSION_KEY: "somerandomstring"
      FORM_ENCRYPTION_KEY: "anotherrandomstring"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST: redis
      REDIS_PORT: 6379
  
  mongo:
    image: mongo:4.4.29-focal
    restart: unless-stopped
    volumes:
      - "data:/data/db"
  
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: "redis-server --appendonly yes"
```

Connection to mongo also succeeds as I can see this in the mongo logs:

```
{"t":{"$date":"2024-04-10T07:43:28.558+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.23.0.4:49896","connectionId":1,"connectionCount":1}}
{"t":{"$date":"2024-04-10T07:43:28.565+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"172.23.0.4:49896","client":"conn1","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-92-generic"},"platform":"'Node.js v18.20.0, LE (unified)","version":"3.7.4|5.13.20"}}}
{"t":{"$date":"2024-04-10T07:43:28.572+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.23.0.4:49908","connectionId":2,"connectionCount":2}}
{"t":{"$date":"2024-04-10T07:43:28.575+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"172.23.0.4:49908","client":"conn2","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-92-generic"},"platform":"'Node.js v18.20.0, LE (unified)","version":"3.7.4|5.13.20"}}}
{"t":{"$date":"2024-04-10T07:43:28.624+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.23.0.4:49918","connectionId":3,"connectionCount":3}}
{"t":{"$date":"2024-04-10T07:43:28.624+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn3","msg":"client metadata","attr":{"remote":"172.23.0.4:49918","client":"conn3","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-92-generic"},"platform":"'Node.js v18.20.0, LE (unified)","version":"3.7.4|5.13.20"}}}
```
