### DISCUSSION TITLE
Persist Data for Docker Compose

### DISCUSSION THREAD

**Discussion by johncadengo** [heyform/heyform#54] [Self hosting]
I have the project set up under Docker Compose following the [self-hosted instructions](https://docs.heyform.net/self-hosting).

From the documentation, I'm using the basic docker-compose.yml file:

```
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    restart: "always"
    depends_on:
      - mongo
      - redis
    ports:
      - "9513:8000"
    environment:
      # The homepage of a website is the URL that you open in your browser
      # The port here should be consistent with the exposed one (should be 9513 NOT 8000)
      APP_HOMEPAGE_URL: http://127.0.0.1:9513
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
```

Recently, I decided to update the images. I ran `docker compose pull` and `docker compose up -d` but then I realized all my data was destroyed.

Then I noticed that in this docker-compose.yml file, there are no persistent volumes.

What volumes should I persist in order to make sure that my data isn't destroyed between bringing a container down and spinning it back up again?

**Comment by iMuFeng** [comment]
For heyform you can: 

```docker
heyform:
  image: heyform/community-edition:latest
  volumes:
    - .:/app
```

**Comment by johncadengo** [comment]
@iMuFeng have you actually tried that? 

When I try it, it doesn't work at all. The server won't even start. 

To give more context, I haven't git cloned this repo. I literally have a folder with a docker-compose.yml file. That's it. In most cases, a self-hosted instance can be deployed with a single docker compose file. Are you expecting that the volume `.:/app` points to the git repo? 

If it's pointing to the folder which doesn't contain the git repo, it won't run. If it's pointing to the git repo, isn't that already in the docker image? Why would pointing to those files persist the data?

I'd think that in order to persist the volume, you'd have to persist the mongo container, no?

**Comment by johncadengo** [comment]
@iMuFeng Since the documentation doesn't live in the Github repo, I'm not able to update it for you. If you were to move it there, I'd be happy to update a README or some doc that helps people get started with self-hosting.

Nonetheless, here's the solution that I tested and found to work.

Add a volume to the mongo container:

```
  mongo:
    image: mongo:4.4.29
    restart: "always"
     volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
```

This should persist data with docker compose. I was able to stop the container, start it again, and then see that the data was still persistent.

**Reply by iMuFeng** [reply]
We will soon be migrating our documents from Notion to GitHub.

**Reply by johncadengo** [reply]
Sounds great. Would be happy to contribute for documentation when possible.

**Comment by mauran** [comment]
+1 for persisting data in the docker-compose example. I'm using [Towerr](https://github.com/containrrr/watchtower) which will update to the latest version of a docker image and just lost my image assets on the latest update. Sadly it also happened with the mongo-db container 😅  - luckily i only used heyform for testing

**Reply by mauran** [reply]
This seems to work fine for me. 

```
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    restart: "always"
    depends_on:
      - mongo
      - redis
    ports:
      - "9513:8000"
    volumes:
      - assets:/app/static/upload
    environment:
      # Your website homepage URL, e.g. http://form.yourcompany.com
      APP_HOMEPAGE_URL: http://form.yourcompany.com
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
volumes:
  assets:
  db:
```
