### DISCUSSION TITLE
Coolify

### DISCUSSION THREAD

**Discussion by boringcommerce** [heyform/heyform#77] [Self hosting]
Is there a straight forward way to install this on coolify?

**Comment by vianmora** [comment]
could be very nice ! 
There's a template on coolify, but it's buggy it seems :/

**Comment by vianmora** [comment]
you can use this docker-compose

(I use ferretdb instead of mongoDB because it lighter)

```
services:
  heyform:
    image: 'heyform/community-edition:latest'
    restart: always
    environment:
      SERVICE_FQDN_HEYFORM_9000: ''
      APP_HOMEPAGE_URL: '${SERVICE_FQDN_HEYFORM_9000}'
      SESSION_KEY: '${SESSION_KEY}'
      MONGO_URI: 'mongodb://heyform:${POSTGRES_PASSWORD}@ferretdb:27017/heyform?authMechanism=PLAIN'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SMTP_HOST: '${SMTP_HOST}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_USER: '${SMTP_USER}'
      SMTP_PASSWORD: '${SMTP_PASSWORD}'
      SMTP_FROM: '${SMTP_FROM}'
    depends_on:
      - ferretdb
      - redis
  ferretdb:
    image: 'ghcr.io/ferretdb/ferretdb:1'
    restart: always
    environment:
      FERRETDB_POSTGRESQL_URL: 'postgres://heyform:${POSTGRES_PASSWORD}@postgres:5432/ferretdb'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:16-alpine'
    restart: always
    environment:
      POSTGRES_DB: ferretdb
      POSTGRES_USER: heyform
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  redis:
    image: 'redis:7-alpine'
    restart: always
    volumes:
      - 'redis_data:/data'
volumes:
  postgres_data: null
  redis_data: null
```
