### DISCUSSION TITLE
Docker compose Instance keep dropping database

### DISCUSSION THREAD

**Discussion by Abz2604** [heyform/heyform#82] [Q&A]
I followed instructions to self host a heyform instance for testing purposes

However I have noticed that the database keeps getting dropped
So each time I visit the instance after some time, the account itself is gone and I have to create an account all over again

I'm using the following compose file

```
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    restart: "always"
    depends_on:
      - mongo
      - redis
    ports:
      - "9513:8000"
    volumes:
      - assets:/app/static/upload
    environment:
      # Your website homepage URL, e.g. http://form.yourcompany.com
      APP_HOMEPAGE_URL:  http://form.yourcompany.com
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
volumes:
  assets:
  db:
```

I also made changes to the compose based on what was suggested in a previous discussion topic

However, the solution doesnt seem to work
And I'm still seeing the account and the forms n all everything gone

Please point me in the right direction

**Comment by Abz2604** [comment]
This is what I see in the logs right after the data goes missing

`
{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-177-generic"},"platform":"CPython 3.8.10.final.0"}}}
{"t":{"$date":"2024-05-08T00:29:52.537+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn22","msg":"dropDatabase - starting","attr":{"db":"READ__ME_TO_RECOVER_YOUR_DATA"}}
{"t":{"$date":"2024-05-08T00:29:52.537+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"READ__ME_TO_RECOVER_YOUR_DATA","namespace":"READ__ME_TO_RECOVER_YOUR_DATA.README"}}
{"t":{"$date":"2024-05-08T00:29:52.541+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn22","msg":"dropDatabase","attr":{"db":"READ__ME_TO_RECOVER_YOUR_DATA","numCollectionsDropped":1}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn22","msg":"dropDatabase - starting","attr":{"db":"heyform"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.MongooseMeta"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.projectmembermodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.integrationmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.projectgroupmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.submissioniplimitmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.teaminvitationmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.projectmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.formmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.formanalyticmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.submissionmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.teammodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.formreportmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.appmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.usersocialaccountmodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.usermodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.templatemodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.teammembermodels"}}
{"t":{"$date":"2024-05-08T00:29:52.901+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"heyform","namespace":"heyform.teamactivitymodels"}}
{"t":{"$date":"2024-05-08T00:29:52.995+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn22","msg":"dropDatabase","attr":{"db":"heyform","numCollectionsDropped":18}}
{"t":{"$date":"2024-05-08T00:29:53.646+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn22","msg":"dropDatabase - starting","attr":{"db":"local"}}
{"t":{"$date":"2024-05-08T00:29:53.646+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn22","msg":"dropDatabase - dropping collection","attr":{"db":"local","namespace":"local.startup_log"}}
{"t":{"$date":"2024-05-08T00:29:53.651+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn22","msg":"dropDatabase","attr":{"db":"local","numCollectionsDropped":1}}
{"t":{"$date":"2024-05-08T00:29:54.010+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"conn22","msg":"createCollection","attr":{"namespace":"READ__ME_TO_RECOVER_YOUR_DATA.README","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"5cdb9cae-8990-428c-8c98-8af3f11db700"}},"options":{}}}
{"t":{"$date":"2024-05-08T00:29:54.025+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"conn22","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"READ__ME_TO_RECOVER_YOUR_DATA.README","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2024-05-08T00:29:54.381+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn22","msg":"Connection ended","attr":{"remote":"173.44.49.91:42624","connectionId":22,"connectionCount":14}}
{"t":{"$date":"2024-05-08T00:29:54.770+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn20","msg":"Interrupted operation as its client disconnected","attr":{"opId":1884}}
{"t":{"$date":"2024-05-08T00:29:54.771+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn20","msg":"Connection ended","attr":{"remote":"173.44.49.91:42614","connectionId":20,"connectionCount":13}}
{"t":{"$date":"2024-05-08T00:29:54.771+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn21","msg":"Connection ended","attr":{"remote":"173.44.49.91:42636","connectionId":21,"connectionCount":12}}
`

**Comment by iMuFeng** [comment]
Please add additional top-level volumes to resolve this issue:

```docker
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    restart: "always"
    volumes:
      # Perist uploaded images
      - assets:/app/static/upload

  mongo:
    image: mongo:4.4.29
    restart: "always"
    volumes:
      # Persist mongodb data
      - database:/data/db
    ports:
      - "17017:27017"

  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    volumes:
      # Persist redis data
      - redis:/data
    ports:
      - "16379:6379"
      
volumes:
  assets:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./assets
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database
  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./redis
```

**Reply by Abz2604** [reply]
Thank you for the prompt response @iMuFeng 

I will do this right away and update you about the results!

**Reply by Abz2604** [reply]
Here is my final docker-compose that I have deployed

```
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    restart: "always"
    depends_on:
      - mongo
      - redis
    ports:
      - "9513:8000"
    volumes:
      - assets:/app/static/upload
    environment:
      # Your website homepage URL, e.g. http://form.yourcompany.com
      APP_HOMEPAGE_URL: http://form.yourcompany.com
      SESSION_KEY: "onekey"
      FORM_ENCRYPTION_KEY: "twokey"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "17017:27017"
    volumes:
      - database:/data/db
   
  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    volumes:
      # Persist redis data
      - redis:/data
    ports:
      - "16379:6379"

volumes:
  assets:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./assets
  
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database
  
  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./redis
```
