### ISSUE TITLE
[Bug]: node:internal/process/promises:288 heyform-1  |             triggerUncaughtException(err, true /* fromPromise */);

### ISSUE THREAD

**Issue by KunSir991** [heyform/heyform#128]
### Bug Description

node:internal/process/promises:288 heyform-1  |             triggerUncaughtException(err, true /* fromPromise */);

### Steps to Reproduce

1. docker compose up -d
2. docker compose logs heyform

heyform-1  | [Nest] 45   - 08/28/2024, 9:32:16 AM   [MongooseModule] projectmembermodels createIndex {"memberId":1} {"background":true}
heyform-1  | node:internal/process/promises:288
heyform-1  |             triggerUncaughtException(err, true /* fromPromise */);
heyform-1  |             ^
heyform-1  | 
heyform-1  | Error: write EPIPE
heyform-1  |     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
heyform-1  |     at __node_internal_errnoException (node:internal/errors:623:12)
heyform-1  |     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
heyform-1  |     at writeGeneric (node:internal/stream_base_commons:151:3)
heyform-1  |     at Socket._writeGeneric (node:net:962:11)
heyform-1  |     at Socket._write (node:net:974:8)
heyform-1  |     at writeOrBuffer (node:internal/streams/writable:392:12)
heyform-1  |     at _write (node:internal/streams/writable:333:10)
heyform-1  |     at Writable.write (node:internal/streams/writable:337:10)
heyform-1  |     at Redis.sendCommand (/app/node_modules/.pnpm/ioredis@4.28.5/node_modules/ioredis/built/redis/index.js:679:33)
heyform-1  |     at Redis.info (/app/node_modules/.pnpm/ioredis@4.28.5/node_modules/ioredis/built/commander.js:122:25)
heyform-1  |     at Redis._readyCheck (/app/node_modules/.pnpm/ioredis@4.28.5/node_modules/ioredis/built/redis/index.js:493:10)
heyform-1  |     at Socket.<anonymous> (/app/node_modules/.pnpm/ioredis@4.28.5/node_modules/ioredis/built/redis/event_handler.js:58:18)
heyform-1  |     at Object.onceWrapper (node:events:631:28)
heyform-1  |     at Socket.emit (node:events:529:35)
heyform-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1540:10) {
heyform-1  |   errno: -32,
heyform-1  |   code: 'EPIPE',
heyform-1  |   syscall: 'write'
heyform-1  | }
heyform-1  | 
heyform-1  | Node.js v18.20.0

### Expected Behavior

node:internal/process/promises:288 heyform-1  |             triggerUncaughtException(err, true /* fromPromise */);

### HeyForm Installation

self hosted

### Version

node:internal/process/promises:288 heyform-1  |             triggerUncaughtException(err, true /* fromPromise */);

### Desktop OS

Linux

### Desktop Browser

Chrome

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

**Comment by iMuFeng** [comment]
I couldn't reproduce this on my computer. Could you please check if Redis server is running?

**Comment by KunSir991** [comment]
> I couldn't reproduce this on my computer. Could you please check if Redis server is running?

![image](https://github.com/user-attachments/assets/e82c04da-fbf6-4699-9430-b8f6e7c312ff)
redis is running

**Comment by iMuFeng** [comment]
Can you paste the `docker-compose.yml` here?

**Comment by KunSir991** [comment]
> Can you paste the `docker-compose.yml` here?

```yaml
version: "3"
services:
  heyform:
    image: heyform/community-edition:latest
    restart: always
    volumes:
      # Persist uploaded images
      - ./assets:/app/static/upload
    depends_on:
      - mongo
      - keydb
    ports:
      - '9513:8000'
    environment:
      APP_HOMEPAGE_URL: http://127.0.0.1:9513
      SESSION_KEY: key1
      FORM_ENCRYPTION_KEY: key2
      MONGO_URI: 'mongodb://mongo:27017/heyform'
      REDIS_HOST: keydb
      REDIS_PORT: 6379
  mongo:
    image: percona/percona-server-mongodb:4.4
    restart: always
    volumes:
      # Persist MongoDB data
      - ./database:/data/db
  keydb:
    image: eqalpha/keydb:latest
    restart: always
    command: keydb-server --appendonly yes
    volumes:
      # Persist KeyDB data
      - ./keydb:/data
```

**Comment by iMuFeng** [comment]
Check if Heyform can connect to KeyDB or not:

```
docker-compose exec heyform ping keydb
docker-compose exec heyform npx redis-cli -h keydb -p 6379 ping
```

You can try the following config to test the network configuration issue:

```
version: '3'

services:
  heyform:
    image: heyform/community-edition:latest
    restart: always
    volumes:
      - ./assets:/app/static/upload
    depends_on:
      - mongo
      - keydb
    ports:
      - '9513:8000'
    environment:
      APP_HOMEPAGE_URL: http://127.0.0.1:9513
      SESSION_KEY: key1
      FORM_ENCRYPTION_KEY: key2
      MONGO_URI: 'mongodb://mongo:27017/heyform'
      REDIS_HOST: keydb
      REDIS_PORT: 6379
    networks:
      - heyform-network

  mongo:
    image: percona/percona-server-mongodb:4.4
    restart: always
    volumes:
      - ./database:/data/db
    networks:
      - heyform-network

  keydb:
    image: eqalpha/keydb:latest
    restart: always
    command: keydb-server --appendonly yes
    volumes:
      - ./keydb:/data
    networks:
      - heyform-network

networks:
  heyform-network:
    driver: bridge
```

**Comment by KunSir991** [comment]
> Check if Heyform can connect to KeyDB or not:
> 
> ```
> docker-compose exec heyform ping keydb
> docker-compose exec heyform npx redis-cli -h keydb -p 6379 ping
> ```
> 
> You can try the following config to test the network configuration issue:
> 
> ```
> version: '3'
> 
> services:
>   heyform:
>     image: heyform/community-edition:latest
>     restart: always
>     volumes:
>       - ./assets:/app/static/upload
>     depends_on:
>       - mongo
>       - keydb
>     ports:
>       - '9513:8000'
>     environment:
>       APP_HOMEPAGE_URL: http://127.0.0.1:9513
>       SESSION_KEY: key1
>       FORM_ENCRYPTION_KEY: key2
>       MONGO_URI: 'mongodb://mongo:27017/heyform'
>       REDIS_HOST: keydb
>       REDIS_PORT: 6379
>     networks:
>       - heyform-network
> 
>   mongo:
>     image: percona/percona-server-mongodb:4.4
>     restart: always
>     volumes:
>       - ./database:/data/db
>     networks:
>       - heyform-network
> 
>   keydb:
>     image: eqalpha/keydb:latest
>     restart: always
>     command: keydb-server --appendonly yes
>     volumes:
>       - ./keydb:/data
>     networks:
>       - heyform-network
> 
> networks:
>   heyform-network:
>     driver: bridge
> ```

Using this docker-compose.yml still reports the same error, Any other solutions?

**Comment by KunSir991** [comment]
Using this docker-compose.yml still reports the same error, Any other solutions?

**Comment by KunSir991** [comment]
```shell
# docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "74af0388eebcccefe6ccff20e5a742142ed31e1f76cf0361ba22e48edae7691c",
        "Created": "2024-08-28T17:48:36.255339053+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]



# docker network inspect root_heyform-network 
[
    {
        "Name": "root_heyform-network",
        "Id": "a40d0e5db72c471408b6832769497b5b41d558716578c70407eccc41f0bd07a2",
        "Created": "2024-08-29T11:04:41.311890045+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4cde2ec27a8e3f956fd4b9672babe398a2c13f2d9404ac5412990aec91ec6052": {
                "Name": "root-mongo-1",
                "EndpointID": "701f330b40346df6de1ae6c4eadc8041a623e1232b40c2d8562576f401f95cdc",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "fda1d9633bc5660154d272db67cea340b26604803ac5b2a2acf6ef99cec24bdf": {
                "Name": "root-keydb-1",
                "EndpointID": "fe87382718ceec76b0a85b094bdc99035b8b827cea02b6db96c65afaab813f83",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "heyform-network",
            "com.docker.compose.project": "root",
            "com.docker.compose.version": "2.27.1"
        }
    }
]

```

After deploying with the new docker compose.yml, the network configuration is as above. I can't see the specific reason. Please continue to solve it.

**Comment by aliuq** [comment]
@iMuFeng Hi, The problem still exists

```yaml
heyform-heyform-1  | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 172.20.50.2:6379
heyform-heyform-1  |     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
heyform-heyform-1  |     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
heyform-heyform-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
heyform-heyform-1  | node:internal/process/promises:288
heyform-heyform-1  |             triggerUncaughtException(err, true /* fromPromise */);
heyform-heyform-1  |             ^
heyform-heyform-1  | 
heyform-heyform-1  | Error: connect ECONNREFUSED 172.20.50.2:6379
heyform-heyform-1  |     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
heyform-heyform-1  |     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
heyform-heyform-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
heyform-heyform-1  |   errno: -111,
heyform-heyform-1  |   code: 'ECONNREFUSED',
heyform-heyform-1  |   syscall: 'connect',
heyform-heyform-1  |   address: '172.20.50.2',
heyform-heyform-1  |   port: 6379
heyform-heyform-1  | }
heyform-heyform-1  | 
heyform-heyform-1  | Node.js v18.20.0
heyform-heyform-1  | 
```

docker-compose.yml

```yaml
services:
  heyform:
    image: heyform/community-edition:latest
    restart: unless-stopped
    depends_on:
      - mongo
      - keydb
    ports:
      - 9513:8000
    environment:
      APP_HOMEPAGE_URL: http://192.168.2.10:9513
      SESSION_KEY: key1
      FORM_ENCRYPTION_KEY: key2
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST: keydb
      REDIS_PORT: 6379

  mongo:
    image: percona/percona-server-mongodb:4.4
    restart: unless-stopped

  keydb:
    image: eqalpha/keydb:latest
    restart: unless-stopped
    command: keydb-server --appendonly yes
```

```bash
docker-compose exec heyform ping keydb

PING keydb (172.20.52.4): 56 data bytes
64 bytes from 172.20.52.4: seq=3 ttl=64 time=2004.184 ms
64 bytes from 172.20.52.4: seq=4 ttl=64 time=1004.147 ms
64 bytes from 172.20.52.4: seq=5 ttl=64 time=4.090 ms
```

```bash
docker-compose exec heyform npx redis-cli -h keydb -p 6379 ping

# No output
```

**Comment by iMuFeng** [comment]
> @iMuFeng Hi, The problem still exists
> 
> ```yaml
> heyform-heyform-1  | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 172.20.50.2:6379
> heyform-heyform-1  |     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
> heyform-heyform-1  |     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
> heyform-heyform-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
> heyform-heyform-1  | node:internal/process/promises:288
> heyform-heyform-1  |             triggerUncaughtException(err, true /* fromPromise */);
> heyform-heyform-1  |             ^
> heyform-heyform-1  | 
> heyform-heyform-1  | Error: connect ECONNREFUSED 172.20.50.2:6379
> heyform-heyform-1  |     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
> heyform-heyform-1  |     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
> heyform-heyform-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
> heyform-heyform-1  |   errno: -111,
> heyform-heyform-1  |   code: 'ECONNREFUSED',
> heyform-heyform-1  |   syscall: 'connect',
> heyform-heyform-1  |   address: '172.20.50.2',
> heyform-heyform-1  |   port: 6379
> heyform-heyform-1  | }
> heyform-heyform-1  | 
> heyform-heyform-1  | Node.js v18.20.0
> heyform-heyform-1  | 
> ```
> 
> docker-compose.yml
> 
> ```yaml
> services:
>   heyform:
>     image: heyform/community-edition:latest
>     restart: unless-stopped
>     depends_on:
>       - mongo
>       - keydb
>     ports:
>       - 9513:8000
>     environment:
>       APP_HOMEPAGE_URL: http://192.168.2.10:9513
>       SESSION_KEY: key1
>       FORM_ENCRYPTION_KEY: key2
>       MONGO_URI: "mongodb://mongo:27017/heyform"
>       REDIS_HOST: keydb
>       REDIS_PORT: 6379
> 
>   mongo:
>     image: percona/percona-server-mongodb:4.4
>     restart: unless-stopped
> 
>   keydb:
>     image: eqalpha/keydb:latest
>     restart: unless-stopped
>     command: keydb-server --appendonly yes
> ```
> 
> ```shell
> docker-compose exec heyform ping keydb
> 
> PING keydb (172.20.52.4): 56 data bytes
> 64 bytes from 172.20.52.4: seq=3 ttl=64 time=2004.184 ms
> 64 bytes from 172.20.52.4: seq=4 ttl=64 time=1004.147 ms
> 64 bytes from 172.20.52.4: seq=5 ttl=64 time=4.090 ms
> ```
> 
> ```shell
> docker-compose exec heyform npx redis-cli -h keydb -p 6379 ping
> 
> # No output
> ```

Is it possible to start up if you switch to redis?

```
  keydb:
    image: redis
    restart: unless-stopped
    command: "redis-server --appendonly yes"
```
