### ISSUE TITLE
[Bug]: After deploying the service with docker, the login cannot redirect to the page after completing the registration, and remains stuck on the login page.

### ISSUE THREAD

**Issue by KunSir991** [heyform/heyform#130]
### Bug Description

[Bug]: After deploying the service with docker, the login cannot redirect to the page after completing the registration, and remains stuck on the login page.

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/73012af9-66a6-4173-97a4-5fc588c6a87f)

### Expected Behavior

[Bug]: After deploying the service with docker, the login cannot redirect to the page after completing the registration, and remains stuck on the login page.

### HeyForm Installation

self hosted

### Version

heyform/community-edition:latest

### Desktop OS

Linux

### Desktop Browser

Chrome

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

**Comment by iMuFeng** [comment]
The `APP_HOMEPAGE_URL` must be equal the one that you are using on your browser.

**Comment by anarion80** [comment]
You need to set it to however you access the service in the browser.

If you just have it in docker on some port then:
`APP_HOMEPAGE_URL : http://docker_host:port`

If you already have some proxy and a domain, then

`APP_HOMEPAGE_URL : https://heyform.domain`

**Comment by da-wilky** [comment]
I am having the same problem. I've definetly set APP_HOMEPAGE_URL correctly.
I can access the page on first load, then create a new user. After clicking the create button there is a permanent redirect happening to `/`. The console permently logs:

```
heyform-1  | [Nest] 18   - 09/25/2025, 12:11:13 PM   [MongooseModule] teammodels find {"_id":{"$in":[]}} {"sort":{"name":1},"projection":{}}
heyform-1  | [Nest] 18   - 09/25/2025, 12:11:13 PM   [MongooseModule] usermodels findOne {"_id":"68d52fe3ac02c60012502b0b"} {"projection":{}}
```

Can anyone help me with this?


My currently used `docker-compose.yml`:
```yml
services:
  heyform:
    image: heyform/community-edition:latest
    restart: always
    volumes:
      # Persist uploaded images
      - ./data/assets:/app/static/upload
    depends_on:
      - mongo
      - keydb
    ports:
      - '8000:8000'
    environment:
      APP_HOMEPAGE_URL: http://my-domain.com:8000
      SESSION_KEY: key1
      FORM_ENCRYPTION_KEY: key2
      MONGO_URI: 'mongodb://mongo:27017/heyform'
      REDIS_HOST: keydb
      REDIS_PORT: 6379

  mongo:
    image: percona/percona-server-mongodb:4.4
    #image: mongo:8-noble
    restart: always
    volumes:
      # Persist MongoDB data
      - mongodb_data:/data/db

  keydb:
    image: eqalpha/keydb:alpine
    restart: always
    command: keydb-server --appendonly yes --protected-mode no
    volumes:
      # Persist KeyDB data
      - ./data/keydb:/data

volumes:
  mongodb_data:
```
