### ISSUE TITLE
Persist Data for Docker Compose

### ISSUE THREAD

**Issue by johncadengo** [heyform/heyform#53]
I have the project set up under Docker Compose following the [self-hosted instructions](https://docs.heyform.net/self-hosting).

From the documentation, I'm using the basic docker-compose.yml file:

```
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    restart: "always"
    depends_on:
      - mongo
      - redis
    ports:
      - "9513:8000"
    environment:
      # The homepage of a website is the URL that you open in your browser
      # The port here should be consistent with the exposed one (should be 9513 NOT 8000)
      APP_HOMEPAGE_URL: http://127.0.0.1:9513
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
```

Recently, I decided to update the images. I ran `docker compose pull` and `docker compose up -d` but then I realized all my data was destroyed.

Then I noticed that in this docker-compose.yml file, there are no persistent volumes.

What volumes should I persist in order to make sure that my data isn't destroyed between bringing a container down and spinning it back up again?
