### ISSUE TITLE
Nodejs error with docker - cannot start Heyform

### ISSUE THREAD

**Issue by arsaboo** [heyform/heyform#7]
Here's the docker-compose file that I am using:
```yaml
version: "3"

services:
  heyform:
    image: heyform/community-edition:latest
    ports:
      - "8001:8000"
    depends_on:
      - mongo
      - redis
    environment:
      APP_HOMEPAGE_URL: http://127.0.0.1:8000
      COOKIE_DOMAIN: 127.0.0.1
      SESSION_MAX_AGE: 15d
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      UPLOAD_FILE_TYPES: ".jpg,.png,.bmp,.gif,.txt,.md,.doc,.docx,.xls,.xlsx,.csv,.ppt,.pptx,.pdf,.mp4,.wmv,.zip,.rar,.7z"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      # Assuming these are the minimum required for your setup
      # Add any other environment variables here that your application cannot run without

  mongo:
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"

```
However, I am getting this error and the heyform container just exits:

```bash
> server@0.0.2 start /app
> node dist/main.js
/app/node_modules/.pnpm/apollo-server@2.26.1_@apollo+client@3.9.9_@types+node@13.9.1_graphql@15.3.0/node_modules/apollo-server/dist/exports.js:17
Object.defineProperty(exports, "GraphQLUpload", { enumerable: true, get: function () { return apollo_server_core_1.GraphQLUpload; } });
       ^
TypeError: Cannot redefine property: GraphQLUpload
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/app/node_modules/.pnpm/apollo-server@2.26.1_@apollo+client@3.9.9_@types+node@13.9.1_graphql@15.3.0/node_modules/apollo-server/dist/exports.js:17:8)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/app/node_modules/.pnpm/apollo-server@2.26.1_@apollo+client@3.9.9_@types+node@13.9.1_graphql@15.3.0/node_modules/apollo-server/dist/index.js:30:14)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/app/dist/utils/directives/lower.js:4:25)
Node.js v18.20.0
 ELIFECYCLE  Command failed with exit code 1.
```
