### ISSUE TITLE
Failed to fetch error when creating a new account

### ISSUE THREAD

**Issue by arsaboo** [heyform/heyform#9]
Here's the compose file:
```yaml
version: "3"

services:
  heyform:
    container_name: heyform_app
    image: heyform/community-edition:latest
    ports:
      - "8001:8000"
    depends_on:
      - mongo
      - redis
    environment:
      APP_HOMEPAGE_URL: http://127.0.0.1:8000
      COOKIE_DOMAIN: 127.0.0.1
      SESSION_MAX_AGE: 15d
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform"
      UPLOAD_FILE_TYPES: ".jpg,.png,.bmp,.gif,.txt,.md,.doc,.docx,.xls,.xlsx,.csv,.ppt,.pptx,.pdf,.mp4,.wmv,.zip,.rar,.7z"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  mongo:
    container_name: heyform_mongo
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /mnt/docker/containers/heyform/mongo:/data/db

  redis:
    container_name: heyform_redis
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - /mnt/docker/containers/heyform/redis/:/data
```
Everything starts now, but I am unable to create an account:

![image](https://github.com/heyform/heyform/assets/18319734/0d389c52-32bf-4966-aa31-3cae2396dfe9)

**Comment by iMuFeng** [comment]
Please update the "APP_HOMEPAGE_URL" in your configuration to `http://127.0.0.1:8001`

**Comment by arsaboo** [comment]
I updated to my domain `https://forms.xyz.com`, but now I am getting the error:

![image](https://github.com/heyform/heyform/assets/18319734/429d91e9-ccca-45c7-ae80-88e0ed9a7bb5)

Here are the logs:
```bash
[Nest] 17   - 04/02/2024, 1:55:57 PM   [MongooseModule] usermodels findOne {"email":"EMAIL"} {"projection":{}}
[Nest] 17   - 04/02/2024, 1:55:57 PM   [ExceptionsHandler] command find requires authentication +3ms
MongoError: command find requires authentication
    at MessageStream.messageHandler (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/connection.js:299:20)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:809:22)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 17   - 04/02/2024, 1:57:22 PM   [MongooseModule] usermodels findOne {"email":"arsaboo@gmail.com"} {"projection":{}}
[Nest] 17   - 04/02/2024, 1:57:22 PM   [ExceptionsHandler] command find requires authentication +2ms
MongoError: command find requires authentication
    at MessageStream.messageHandler (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/connection.js:299:20)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:809:22)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)```

**Comment by iMuFeng** [comment]
> I updated to my domain `https://forms.xyz.com`, but now I am getting the error:
> 
> ![image](https://private-user-images.githubusercontent.com/18319734/318808517-429d91e9-ccca-45c7-ae80-88e0ed9a7bb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjcwNDAsIm5iZiI6MTcxMjA2Njc0MCwicGF0aCI6Ii8xODMxOTczNC8zMTg4MDg1MTctNDI5ZDkxZTktY2NjYS00NWM3LWFlODAtODhlMGVkOWE3YmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MzNkMGYxMjMyMGUwYzRkNjgxMTg1NzUxMjM1MjU2NWM3ODk1NzAzODM1NGM4MDA1NWJiNzdjYjNiN2E5NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lT54Ljh4jrBGbK8qpI2U4Fltu6AHvXgMHo67ZCJpm1U)
> 
> Here are the logs:
> 
> ```shell
> [Nest] 17   - 04/02/2024, 1:55:57 PM   [MongooseModule] usermodels findOne {"email":"EMAIL"} {"projection":{}}
> [Nest] 17   - 04/02/2024, 1:55:57 PM   [ExceptionsHandler] command find requires authentication +3ms
> MongoError: command find requires authentication
>     at MessageStream.messageHandler (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/connection.js:299:20)
>     at MessageStream.emit (node:events:517:28)
>     at processIncomingData (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
>     at MessageStream._write (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
>     at writeOrBuffer (node:internal/streams/writable:392:12)
>     at _write (node:internal/streams/writable:333:10)
>     at Writable.write (node:internal/streams/writable:337:10)
>     at Socket.ondata (node:internal/streams/readable:809:22)
>     at Socket.emit (node:events:517:28)
>     at addChunk (node:internal/streams/readable:368:12)
>     at readableAddChunk (node:internal/streams/readable:341:9)
>     at Readable.push (node:internal/streams/readable:278:10)
>     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
> [Nest] 17   - 04/02/2024, 1:57:22 PM   [MongooseModule] usermodels findOne {"email":"EMAIL"} {"projection":{}}
> [Nest] 17   - 04/02/2024, 1:57:22 PM   [ExceptionsHandler] command find requires authentication +2ms
> MongoError: command find requires authentication
>     at MessageStream.messageHandler (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/connection.js:299:20)
>     at MessageStream.emit (node:events:517:28)
>     at processIncomingData (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
>     at MessageStream._write (/app/node_modules/.pnpm/mongodb@3.7.4/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
>     at writeOrBuffer (node:internal/streams/writable:392:12)
>     at _write (node:internal/streams/writable:333:10)
>     at Writable.write (node:internal/streams/writable:337:10)
>     at Socket.ondata (node:internal/streams/readable:809:22)
>     at Socket.emit (node:events:517:28)
>     at addChunk (node:internal/streams/readable:368:12)
>     at readableAddChunk (node:internal/streams/readable:341:9)
>     at Readable.push (node:internal/streams/readable:278:10)
>     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)```
> ```

```
version: "3"

services:
  heyform:
    container_name: heyform_app
    image: heyform/community-edition:latest
    ports:
      - "8001:8000"
    depends_on:
      - mongo
      - redis
    environment:
      APP_HOMEPAGE_URL: http://127.0.0.1:8001
      SESSION_MAX_AGE: 15d
      SESSION_KEY: "key1"
      FORM_ENCRYPTION_KEY: "key2"
      MONGO_URI: "mongodb://mongo:27017/heyform?authSource=admin"
      MONGO_USER: "root"
      MONGO_PASSWORD: "example"
      UPLOAD_FILE_TYPES: ".jpg,.png,.bmp,.gif,.txt,.md,.doc,.docx,.xls,.xlsx,.csv,.ppt,.pptx,.pdf,.mp4,.wmv,.zip,.rar,.7z"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  mongo:
    container_name: heyform_mongo
    image: mongo:4.4.29
    restart: "always"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /mnt/docker/containers/heyform/mongo:/data/db

  redis:
    container_name: heyform_redis
    image: redis
    restart: "always"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - /mnt/docker/containers/heyform/redis/:/data
```
